define({
  root: ({
    showLegend: "Show legend",
    controlPopupMenuTitle: "Choose which actions will be shown on the layer context menu",
    zoomto: "Zoom to",
    transparency: "Transparency",
    controlPopup: "Enable / Disable pop-up",
    moveUpAndDown: "Move up / Move down",
    attributeTable: "View in Attribute Table",
	visibilityRange: "Show Visibility Range(2.12 version or above)",
    url: "Description / Show item details / Download",
    expandAllLayers: "Expand all layers",
    expandAllLayersByDefault: "Expand all layers by default",
    layerSelectorTitle: "Choose which layers will be shown on the list",
    showTitle: "Show title",
    showBasemap: "Show Basemap",
    titlebookmarks: 'Bookmarks',
    placeholderFolderName: 'Folder Name',
    errorNameExist: 'Name exists!',
    errorNameNull: "Invalid folder name!",
    labelDelete: "Delete",
    labelEdit: "Edit",
    labelBookmarkName: "Bookmark the current view",
    clearSelected: "Clear Selected",
    clearToolTip: "The selected node in the tree will determine where a new bookmark is added. To add a new bookmark in the root of the tree you need to clear the current selected node.",
    webmapfoldername: "Webmap Bookmarks",
    errorWebmapNode: "You can not add a  folder to the webmap folder.",
    thumbPreview: "Preview the bookmark thumbnail image.",
    bookmarkPreview: "Bookmark Preview",
    bookmarkThumbnail: "Bookmark thumbnail",
    widgetactions: "Actions Menu",
    addFolder: "Add Folder",
    saveBookmarks: "Save Bookmarks",
    expanded: "Folder expanded",
    cancel: "Cancel",
    add: "Add",
    ok: "Ok",
    title: "Folder name",      
    warning: "Please finish the edit!",
    edit: "Edit bookmark",
    editFolder: "Edit folder Name",
    thumbnail: "Thumbnail",
    thumbnailHint: "Click the image to update",
    addBookmarks: "Allow adding bookmarks or folders in the widget",
    _addBookmark: "Add Bookmark",
    extentThumbnailHint: "Add the map image below as the thumbnail",
    addMapImage: "Add Map Image",
    or: "Or",
    moveup: "Move up",
    movedown: "Move down",
    customfoldersDiv: "Add layers to custom folders",
    addFolder: "Add Folder",
    deleteLabel: "Delete Folder",
    deleteContent: "Do you want to delete the folder ?",
    foldernameexists: "Folder Name Exits! ",
    selectLayers: "Please select the layers",
    selectLayersfromlayersList: "Please select the layers from layerlist",
    movingnotpossible: "Layer moving is not possible, please select layer from custom folders.",
    emptyfolder: "Folder is empty!",
    layerNotmoving: "No layers found for moving",
     MoveAllcontentToright:"Move all layers/tables to right"


  }),
  "ar": 1,
  "bs": 1,
  "ca": 1,
  "cs": 1,
  "da": 1,
  "de": 1,
  "el": 1,
  "es": 1,
  "et": 1,
  "fi": 1,
  "fr": 1,
  "he": 1,
  "hi": 1,
  "hr": 1,
  "hu": 1,
  "it": 1,
  "id": 1,
  "ja": 1,
  "ko": 1,
  "lt": 1,
  "lv": 1,
  "nb": 1,
  "nl": 1,
  "pl": 1,
  "pt-br": 1,
  "pt-pt": 1,
  "ro": 1,
  "ru": 1,
  "sl": 1,
  "sr": 1,
  "sv": 1,
  "th": 1,
  "tr": 1,
  "vi": 1,
  "zh-cn": 1,
  "zh-hk": 1,
  "zh-tw": 1
});
